runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /Pages
  static_dir: Pages
  application_readable: true

- url: /css
  static_dir: css
  application_readable: true

- url: /fonts
  static_dir: fonts
  application_readable: true

- url: /js
  static_dir: js
  application_readable: true

- url: /Pages
  static_dir: Pages
  application_readable: true

- url: /vendors
  static_dir: vendors

- url: /dropzone
  static_dir: dropzone
  application_readable: true

- url: /.*
  script: connexus.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
